apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-task-configuration-api App
name: wa-wa-task-configuration-api
home: https://github.com/hmcts/wa-task-configuration-api
version: 0.0.1
maintainers:
  - name: HMCTS wa team
dependencies:
  - name: java
    version: 3.0.2
    repository: '@hmctspublic'
