java:
  applicationPort: 8091
  image: 'hmctspublic.azurecr.io/wa/task-configuration-api:latest'
  ingressHost: wa-task-configuration-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: wa
  environment:
    CAMUNDA_URL: "http://camunda-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/engine-rest"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    wa:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: wa-system-username
          alias: WA_SYSTEM_USERNAME
        - name: wa-system-password
          alias: WA_SYSTEM_PASSWORD
        - name: wa-idam-client-id
          alias: WA_IDAM_CLIENT_ID
        - name: wa-idam-client-secret
          alias: WA_IDAM_CLIENT_SECRET
        - name: s2s-secret-task-configuration-api
          alias: S2S_SECRET_TASK_CONFIGURATION_API
        - name: ld-secret
          alias: LAUNCH_DARKLY_SDK_KEY
