server:
  port: 8091

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

config:
  enableSwagger: ${ENABLE_SWAGGER:true}

role-assignment-service:
  url: ${ROLE_ASSIGNMENT_URL:http://role-assignment}

camunda:
  url: ${CAMUNDA_URL:http://camunda-local-bpm/engine-rest}

ccd:
  url: ${CCD_URL:http://ccd-data-store-api}
core_case_data:
  api:
    url: ${CCD_URL:http://ccd-data-store-api}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-resources/**"
    - "/swagger-ui/**"
    - "/swagger-ui/index.html"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"

auth:
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://service-auth-provider-api}

idam:
  baseUrl: ${IDAM_URL:http://sidam-api}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  scope: "openid profile roles"
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_TASK_CONFIGURATION_API:AAAAAAAAAAAAAAAC}
    name: wa_task_configuration_api
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:wa_task_configuration_api,camunda_bpm}
  system:
    username: ${WA_SYSTEM_USERNAME:some_user@hmcts.net}
    password: ${WA_SYSTEM_PASSWORD:password}
  api:
    baseUrl: ${IDAM_API_URL:http://sidam-api}

spring:
  application:
    name: WA Task Configuration
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${WA_IDAM_CLIENT_ID:wa}
            client-secret: ${WA_IDAM_CLIENT_SECRET:something}

launchDarkly:
  sdkKey: ${LAUNCH_DARKLY_SDK_KEY:sdk-key}
  connectionTimeout: 5000
  socketTimeout: 5000

logging:
  level:
    root: INFO
    uk.gov.hmcts.reform.wataskmanagementapi.clients.*: DEBUG
    org.zalando.logbook: TRACE

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic

logbook:
  include: /task/**
